import { launchChrome } from './chrome.mjs';
import { feishuFixture } from './feishu-fixture.mjs';
import assert from 'node:assert/strict';
import path from 'node:path';
import { mkdtemp } from 'node:fs/promises';
import os from 'node:os';
const profile=await mkdtemp(path.join(os.tmpdir(),'wetrim-issue63-'));
const server=feishuFixture();let browser,page,extensionId;
async function launch(first=false){
 browser=await launchChrome({headless:true,userDataDir:profile,enableExtensions:[path.resolve('dist')],args:['--no-sandbox']});
 const worker=await(await browser.waitForTarget(t=>t.type()==='service_worker')).worker();
 const id=await worker.evaluate(()=>chrome.runtime.id);if(extensionId)assert.equal(id,extensionId);extensionId=id;
 // 不复用上次窗口；完整进程关闭后重新打开同一扩展身份和 profile。
 for(const existing of await browser.pages())await existing.close();
 page=await browser.newPage();page.setDefaultTimeout(6000);await server.install(page);
 await page.goto(`chrome-extension://${id}/app.html`);
 await page.waitForSelector('[data-view-mode]');await server.seed(page,first);
}
const status=text=>page.waitForFunction(text=>document.querySelector('[data-feishu-save-status]')?.textContent.includes(text)&&!document.querySelector('[data-feishu-retry]').disabled,{},text);
const local=()=>page.evaluate(()=>chrome.storage.local.get(null));
async function capture(){await page.evaluate(()=>window.__wetrim.processCaptureResult({kind:'article',source:{title:'重启恢复文章',account:'测试来源',publishedAt:'2026-10-08',url:'https://mp.weixin.qq.com/s/restart'},contentHtml:'<p>固定正文</p><p><img src="https://mmbiz.qpic.cn/restart-a.png"></p><p><img src="https://mmbiz.qpic.cn/restart-b.png"></p>',unstable:false}));await page.waitForSelector('[data-feishu-save]');}
try {
 await launch(true);await capture();
 await page.click('[data-feishu-tags-open]');await page.waitForSelector('[data-feishu-tags-new]');await page.type('[data-feishu-tags-new]','重启标签');await page.click('[data-feishu-tags-apply]');
 server.uploadRejectAt=2;
 await page.click('[data-feishu-save]');await status('飞书拒绝');
 const before=await local();assert.equal(before.feishuSave.completed,false);assert.ok(before.feishuSave.images[0].fileToken);assert.equal(before.feishuSave.images[1].fileToken,undefined);
 const fixedGroup=before.feishuSave.group;const recordCount=server.records.length;
 assert.deepEqual(before.feishuSave.values.tags,['重启标签']);
 for(const image of before.feishuSave.images)assert.ok(Object.keys(image).every(key=>['url','fileName','size','sha256','fileToken'].includes(key)),'图片只保存来源与核对元数据');
 // 清洗记录独立不存在，保存恢复仍可执行。只处理测试自己的 local 数据。
 server.images.set('https://mmbiz.qpic.cn/restart-a.png',false);
 await page.evaluate(()=>chrome.storage.local.remove('currentSession'));
 await browser.close();await launch();
 await status('未完成');
 await page.click('[data-feishu-retry]');await status('已保存');
 assert.equal(server.records.length,recordCount);assert.equal(server.records[0].fields['文章关联标识'],fixedGroup);assert.equal(server.records[0].fields['图片'].length,2);
 assert.equal(server.uploadCount,3,'第一张回执复用，只补第二张');
 assert.deepEqual(server.records[0].fields['标签'],['重启标签']);assert.equal(server.records[0].fields['保存时间'],before.feishuSave.values.savedAt);
 assert.equal((await local()).currentSession,undefined,'不重建清洗会话');
 console.log('✓ 完整浏览器重启，同 profile 恢复独立于清洗会话、复用回执并补齐未上传图片');
 server.images.delete('https://mmbiz.qpic.cn/restart-a.png');
 await capture();server.uploadRejectAt=server.uploadCount+2;
 await page.click('[data-feishu-save]');await status('已有保存结果');await page.click('[data-feishu-duplicate]');await status('飞书拒绝');
 const incomplete=await local();const remoteBefore=structuredClone(server.records);
 assert.equal(JSON.stringify(incomplete).includes(server.imageBytes.toString('base64')),false,'不持久化图片二进制');
 server.images.set('https://mmbiz.qpic.cn/restart-b.png',false);
 await browser.close();await launch();await status('未完成');
 const writesBefore=server.writes;await page.click('[data-feishu-retry]');await status('图片无法下载');
 assert.equal(server.writes,writesBefore);assert.deepEqual(server.records,remoteBefore);
 await page.click('[data-feishu-copy-recovery]');await page.click('[data-feishu-copy-confirm]');await status('图片无法下载');
 assert.equal((await local()).feishuSave.group,incomplete.feishuSave.group,'另存预检失败不丢原恢复计划');assert.equal(server.writes,writesBefore);
 await page.click('[data-feishu-abandon]');await page.waitForSelector('[data-feishu-abandon-confirm]');
 assert.match(await page.$eval('[data-feishu-recovery-confirm]',el=>el.textContent),/远端.*保留/);
 await page.click('[data-feishu-abandon-cancel]');assert.ok((await local()).feishuSave);
 await page.click('[data-feishu-abandon]');await page.click('[data-feishu-abandon-confirm]');await status('已放弃');
 const abandoned=await local();assert.equal(abandoned.feishuSave,undefined);assert.deepEqual(abandoned.currentSession,incomplete.currentSession);assert.deepEqual(server.records,remoteBefore);
 assert.ok(abandoned.feishuConnection);console.log('✓ 图片源失效仍未完成；放弃需确认，仅清恢复内容，保留清洗会话、连接与远端部分');
 server.images.delete('https://mmbiz.qpic.cn/restart-b.png');server.fault='lost';
 await page.click('[data-feishu-save]');await status('已有保存结果');await page.click('[data-feishu-duplicate]');await status('需要核对');
 const conflictPlan=(await local()).feishuSave;const changed=server.records.at(-1);changed.fields['正文']='人工修改，不得覆盖';
 await browser.close();await launch();await status('未完成');
 const conflictWrites=server.writes;await page.click('[data-feishu-retry]');await status('远端内容已被修改');assert.equal(server.writes,conflictWrites);
 await page.click('[data-feishu-copy-recovery]');await page.waitForSelector('[data-feishu-copy-confirm]');
 assert.match(await page.$eval('[data-feishu-recovery-confirm]',el=>el.textContent),/固定内容/);
 await page.click('[data-feishu-copy-confirm]');await status('已保存');
 assert.equal(changed.fields['正文'],'人工修改，不得覆盖');assert.equal(server.records.at(-1).fields['正文'],conflictPlan.values.body);
 assert.notEqual(server.records.at(-1).fields['文章关联标识'],conflictPlan.group);assert.equal(server.records.at(-1).fields['图片'].length,2);
 console.log('✓ 重启后人工修改暂停；明确另存固定完整结果，新组不覆盖旧记录');
 const begin=async()=>{await page.click('[data-feishu-save]');await status('已有保存结果');await page.click('[data-feishu-duplicate]');};
 server.imageFault='associateReject';await begin();await status('飞书拒绝');
 const receiptPlan=(await local()).feishuSave;const receiptToken=receiptPlan.images[0].fileToken;
 const validBytes=server.uploads.get(receiptToken);server.uploads.delete(receiptToken);
 await browser.close();await launch();await status('未完成');
 const receiptWrites=server.writes;const uploadCount=server.uploadCount;
 await page.click('[data-feishu-retry]');await status('图片副本无法读取');assert.equal(server.writes,receiptWrites);assert.equal(server.uploadCount,uploadCount);
 server.uploads.set(receiptToken,Buffer.from('changed image bytes'));
 await page.click('[data-feishu-retry]');await status('图片副本内容不一致');assert.equal(server.writes,receiptWrites);
 server.uploads.set(receiptToken,validBytes);
 const receiptRecord=server.records.at(-1);receiptRecord.fields['分篇序号']='1';receiptRecord.fields['分篇总数']='1';receiptRecord.fields['保存时间']=String(receiptRecord.fields['保存时间']);
 await page.click('[data-feishu-retry]');await status('已保存');assert.equal(server.uploadCount,uploadCount);
 console.log('✓ 回执失效或字节变化暂停不重传；回执恢复后按数字字段类型归一，继续原组');
 server.fault='lost';await begin();await status('需要核对');const unknownGroup=(await local()).feishuSave.group;
 server.hide=true;await browser.close();await launch();await status('未完成');
 const unknownWrites=server.writes;await page.click('[data-feishu-retry]');await status('保存结果待确认');assert.equal(server.writes,unknownWrites);
 assert.equal((await local()).feishuSave.group,unknownGroup);server.hide=false;
 await page.click('[data-feishu-retry]');await status('已保存');
 server.imageFault='associateReject';await begin();await status('飞书拒绝');const deleted=server.records.pop();
 await browser.close();await launch();await status('未完成');const deletionWrites=server.writes;
 await page.click('[data-feishu-retry]');await status('已删除');assert.equal(server.writes,deletionWrites);assert.ok((await local()).feishuSave);
 server.records.push(deleted);server.failRecords=true;
 await page.click('[data-feishu-retry]');await status('飞书拒绝');assert.equal(server.writes,deletionWrites);
 server.failRecords=false;server.failFields=true;
 await page.click('[data-feishu-retry]');await status('飞书拒绝');assert.equal(server.writes,deletionWrites);server.failFields=false;
 await page.click('[data-feishu-retry]');await status('已保存');
 console.log('✓ 重启后回执未知暂不可见不重建，记录删除/不可读/字段读取失败均暂停，修复后核对继续');
 const testStatus=text=>page.waitForFunction(text=>document.querySelector('[data-feishu-test-status]')?.textContent.includes(text)&&!document.querySelector('[data-feishu-test-retry]').disabled,{},text);
 await page.click('[data-feishu-settings]');server.imageFault='uploadReject';
 await page.click('[data-feishu-test-start]');await testStatus('飞书拒绝');
 const testBefore=(await local()).feishuSave;assert.equal(testBefore.testSample,true);assert.equal(testBefore.images[0].fileToken,undefined);
 await browser.close();await launch();await status('未完成');await page.click('[data-feishu-settings]');
 await page.click('[data-feishu-test-retry]');await testStatus('正文与图片写入通过');
 assert.equal(server.records.at(-1).fields['文章关联标识'],testBefore.group);assert.equal(server.records.at(-1).fields['图片'].length,1);
 assert.equal((await local()).feishuSave.testSample,true,'重启保留固定测试样例标记');
 // 测试保存与文章恢复共用另存协调器，内置图仍可获取而不走普通域下载。
 server.imageFault='associateReject';await page.click('[data-feishu-test-start]');await testStatus('飞书拒绝');
 const oldTest=server.records.at(-1);oldTest.fields['正文']='人工改动测试记录';
 await browser.close();await launch();await status('未完成');await page.click('[data-feishu-retry]');await status('远端内容已被修改');
 await page.click('[data-feishu-copy-recovery]');await page.click('[data-feishu-copy-confirm]');await status('已保存');
 assert.equal(oldTest.fields['正文'],'人工改动测试记录');assert.equal(server.records.at(-1).fields['图片'].length,1);assert.equal((await local()).feishuSave.testSample,true);
 console.log('✓ 测试保存未上传内置图片跨重启恢复；冲突后另存保留样例标记和完整图片');


 // 两篇共享图片：后篇创建拒绝/未知均在真正重启后继续同一组。
 await page.evaluate(()=>window.__wetrim.processCaptureResult({kind:'article',source:{title:'跨篇重启',account:'测试来源',publishedAt:'2026-10-08',url:'https://mp.weixin.qq.com/s/restart-parts'},contentHtml:'<p>原文</p>',unstable:false}));
 await page.waitForSelector('[data-testid="candidate-btn-replace"]');await page.click('[data-testid="candidate-btn-replace"]');
 await page.waitForFunction(()=>!document.querySelector('.candidate-confirm-dialog[open]'));
 await page.waitForSelector('[data-feishu-save]');
 const shared='https://mmbiz.qpic.cn/restart-shared.png',later='https://mmbiz.qpic.cn/restart-later.png';
 const full='甲'.repeat(85000)+`\n\n![共享](${shared})\n\n`+'乙'.repeat(85000)+`\n\n![再次共享](${shared})\n\n![后篇](${later})`;
 await page.click('[data-block-order="1"] [data-testid="block-action-edit"]');
 await page.waitForSelector('[data-block-order="1"] textarea');
 await page.$eval('[data-block-order="1"] textarea',(el,value)=>{Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));},full);
 await page.click('[data-block-order="1"] [data-testid="block-action-finish-edit"]');
 await page.click('[data-feishu-tags-open]');await page.waitForSelector('[data-feishu-tags-new]');await page.type('[data-feishu-tags-new]','跨篇固定');await page.click('[data-feishu-tags-apply]');
 server.rejectWriteAt=server.writes+4;const uploadsBeforeParts=server.uploadCount;
 await page.click('[data-feishu-save]');await status('飞书拒绝');
 const partial=(await local()).feishuSave;assert.equal(partial.parts.length,1);assert.ok(partial.recordId);assert.equal(partial.parts[0].recordId,undefined);
 server.images.set(shared,false);await browser.close();await launch();await status('未完成');
 await page.click('[data-feishu-retry]');await status('已保存');
 const groupRecords=group=>server.records.filter(r=>r.fields['文章关联标识']===group);
 const original=groupRecords(partial.group);assert.equal(original.length,2);assert.equal(original.map(r=>r.fields['正文']).join(''),full);
 assert.equal(server.uploadCount-uploadsBeforeParts,2,'重启后跨篇共享回执复用，仅上传两项资源');
 assert.equal(original[0].fields['图片'][0].file_token,original[1].fields['图片'][0].file_token);
 assert(original.every(r=>r.fields['保存时间']===partial.values.savedAt&&JSON.stringify(r.fields['标签'])===JSON.stringify(partial.values.tags)));
 server.images.delete(shared);server.loseWriteAt=server.writes+4;await begin();await status('需要核对');
 const unknownParts=(await local()).feishuSave;assert.equal(unknownParts.parts[0].pending,'create');
 server.hide=true;await browser.close();await launch();await status('未完成');const hiddenWrites=server.writes;
 await page.click('[data-feishu-retry]');await status('保存结果待确认');assert.equal(server.writes,hiddenWrites);
 server.hide=false;await page.click('[data-feishu-retry]');await status('已保存');assert.equal(groupRecords(unknownParts.group).length,2);
 server.loseWriteAt=server.writes+4;await begin();await status('需要核对');
 const conflictParts=(await local()).feishuSave;const oldParts=groupRecords(conflictParts.group);oldParts[1].fields['正文']='后篇人工修改';
 await browser.close();await launch();await status('未完成');const oldWrites=server.writes;
 await page.click('[data-feishu-retry]');await status('远端内容已被修改');assert.equal(server.writes,oldWrites);
 const preserved=structuredClone(oldParts);server.images.set(later,false);
 await page.click('[data-feishu-copy-recovery]');await page.click('[data-feishu-copy-confirm]');await status('图片无法下载');
 assert.equal((await local()).feishuSave.group,conflictParts.group);assert.equal(server.writes,oldWrites,'后篇图片预检失败也不能提前写首篇');
 server.images.delete(later);const copyUploads=server.uploadCount;
 await page.click('[data-feishu-copy-recovery]');await page.click('[data-feishu-copy-confirm]');await status('已保存');
 const copied=(await local()).feishuSave;const copies=groupRecords(copied.group);assert.notEqual(copied.group,conflictParts.group);assert.equal(copies.length,2);
 assert.equal(copies.map(r=>r.fields['正文']).join(''),full);assert.deepEqual(oldParts,preserved);
 assert.equal(server.uploadCount-copyUploads,2,'另存完整组重新上传且跨篇仍去重');
 assert(copies.every((r,i)=>r.fields['分篇序号']===i+1&&r.fields['分篇总数']===2&&r.fields['保存时间']===copied.values.savedAt&&JSON.stringify(r.fields['标签'])===JSON.stringify(conflictParts.values.tags)));
 assert.equal(copied.parts[0].group,copied.group);assert.notEqual(copied.parts[0].recordId,conflictParts.parts[0].recordId);assert.equal(copied.parts[0].pending,null);assert.equal(copied.parts[0].pendingUpload,null);assert.equal(copied.parts[0].completed,false);
 console.log('✓ 多篇真实重启：后篇拒绝/未知、跨篇共享回执复用；冲突另存全组预检、固定正文标签及全新回执');

} finally {if(browser?.connected)await browser.close();}
