import { launchChrome } from './chrome.mjs';
import assert from 'node:assert/strict';
import path from 'node:path';
import fs from 'node:fs/promises';
const browser = await launchChrome({ headless: true, enableExtensions: [path.resolve('dist')], args: ['--no-sandbox'] });
try {
 const worker = await (await browser.waitForTarget(t => t.type() === 'service_worker')).worker();
 const page = await browser.newPage(); page.setDefaultTimeout(5000);
 const names = ['标题','公众号名称','原文链接','原文发布日期','保存时间','正文','标签','图片','文章关联标识','分篇序号','分篇总数','保存状态'];
 const types = [1,1,15,5,5,1,4,17,1,2,2,3];
 let fields = names.map((name,i) => ({ field_id: `fld${i}`, field_name: name, type: types[i], ...(i === 11 ? {property:{options:[{name:'未完成'},{name:'已完成'}]}} : {}) }));
 let requests = []; let denyApi = false;
 await page.setRequestInterception(true);
 page.on('request', async request => {
  if (!request.url().startsWith('https://base-api.feishu.cn/')) return request.continue();
  if (request.method() === 'OPTIONS') return request.respond({status:204,headers:{'access-control-allow-origin':'*','access-control-allow-headers':'authorization'}});
  requests.push({method:request.method(), url:request.url()});
  const url = new URL(request.url());
  const data = url.pathname.endsWith('/fields') ? { items: fields, has_more:false } : url.pathname.endsWith('/tables') ? {items:[{table_id:'tblFixture',name:'我的副本'}],has_more:false} : {app:{name:'个人知识库'}};
  await request.respond({status:denyApi ? 403 : 200,headers:{'access-control-allow-origin':'*','access-control-allow-headers':'authorization'},contentType:'application/json',body:JSON.stringify(denyApi ? {code:99991663,msg:'test-secret-never-render'} : {code:0,data})});
 });
 // 显式权限响应替身：不授予/撤销 Chrome 权限，不声称验证原生弹窗。
 const installPermissionResponses = () => page.evaluate(() => {
  window.permissionAllowed = true;
  chrome.permissions.request = async () => window.permissionAllowed;
  chrome.permissions.contains = async () => window.permissionAllowed;
 });
 const appUrl = `chrome-extension://${await worker.evaluate(() => chrome.runtime.id)}/app.html`;
 await page.goto(appUrl);
 await installPermissionResponses();
 await page.waitForSelector('summary[data-feishu-settings]');
 await page.click('summary[data-feishu-settings]');
 const fill = async (selector,value) => { await page.focus(selector); await page.keyboard.down('Control'); await page.keyboard.press('A'); await page.keyboard.up('Control'); await page.keyboard.press('Backspace'); await page.type(selector,value); };
 const status = text => page.waitForFunction(text => document.querySelector('[data-feishu-status]').textContent.includes(text) && !document.querySelector('[data-feishu-check]').disabled,{},text);
 await fill('#feishu-url','https://evil.example/base/abc?table=tbl1');
 await fill('#feishu-token','test-secret-never-render');
 await page.click('[data-feishu-check]'); await status('重新复制');
 assert(!await page.$('[data-feishu-confirm]')); assert.equal(requests.length,0);
 await fill('#feishu-url','https://example.feishu.cn/base/appFixture');
 await page.click('[data-feishu-check]'); await status('重新复制'); assert.equal(requests.length,0);
 await fill('#feishu-url','https://example.feishu.cn/base/appFixture?table=tblFixture&view=vewOther');
 await page.evaluate(() => { window.permissionAllowed = false; });
 await page.click('[data-feishu-check]'); await status('浏览器未允许'); assert.equal(requests.length,0);
 await page.evaluate(() => { window.permissionAllowed = true; });
 await page.click('[data-feishu-check]'); await status('连接检查通过');
 assert.equal(await page.evaluate(async () => (await chrome.storage.local.get('feishuConnection')).feishuConnection),undefined,'确认前不保存配置');
 assert((await page.$eval('.feishu-settings',el => el.innerText)).includes('个人知识库 / 我的副本'));
 await fs.mkdir('artifacts/issue58',{recursive:true});
 await page.screenshot({path:'artifacts/issue58/connection-confirm.png',fullPage:true});
 await page.click('[data-feishu-confirm]'); await status('连接已保存');
 await page.reload(); await installPermissionResponses(); await page.waitForSelector('summary[data-feishu-settings]'); await page.click('summary[data-feishu-settings]'); await status('已连接');
 assert.equal(await page.$eval('#feishu-url',el => el.value),'https://example.feishu.cn/base/appFixture?table=tblFixture');
 fields[0].field_name = '我改名的标题';
 await page.click('[data-feishu-check]'); await status('连接检查通过');
 assert((await page.$eval('.feishu-settings',el => el.innerText)).includes('标题 → 我改名的标题'));
 const statusField = fields.pop();
 await page.click('[data-feishu-check]'); await status('十一列模板'); assert(!await page.$('[data-feishu-confirm]'));
 fields.push(statusField); fields[0].type=2;
 await page.click('[data-feishu-check]'); await status('字段类型不兼容');
 fields[0].type=1; fields[11].property.options=[{name:'未完成'}];
 await page.click('[data-feishu-check]'); await status('缺少未完成／已完成');
 fields[11].property.options.push({name:'已完成'}); fields.push({field_id:'extra',field_name:'额外列',type:1});
 await page.click('[data-feishu-check]'); await status('连接检查通过');
 const originalTitle = fields.shift();
 await page.click('[data-feishu-check]'); await status('缺少或无法唯一识别');
 fields.unshift({...originalTitle,field_id:'fldRecreatedTitle',field_name:'标题'});
 await page.click('[data-feishu-check]'); await status('缺少或无法唯一识别');
 assert(!await page.$('[data-feishu-confirm]'),'同名重建不能自动重绑旧 ID');
 await page.click('[data-feishu-remap]'); await status('连接检查通过');
 await page.click('[data-feishu-confirm]'); await status('连接已保存');
 await page.reload(); await installPermissionResponses(); await page.waitForSelector('summary[data-feishu-settings]'); await page.click('summary[data-feishu-settings]'); await status('已连接');
 await page.click('[data-feishu-check]'); await status('连接检查通过');
 denyApi=true;
 await page.click('[data-feishu-check]'); await status('飞书鉴权失败');
 assert(!await page.evaluate(() => document.body.innerText.includes('test-secret-never-render')));
 assert(requests.length>0 && requests.every(request => request.method === 'GET'),'检查全过程只读，零远端写入');
 const sync = await page.evaluate(() => chrome.storage.sync.get(null)); assert.equal(sync.feishuConnection,undefined);
 console.log('✓ 真实构建界面：链接校验、权限响应替身、目标确认、本地重载、按 ID 改名、十一列/类型/状态阻止、修复恢复、额外列、鉴权脱敏、只读零写入');
 console.log('未验证：真人原生权限授予/拒绝/撤销、真实 API、可访问十二列模板跨账号复制。');
} finally { await browser.close(); }
